version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15
    container_name: cloudbp-postgres
    environment:
      POSTGRES_DB: cloudbp
      POSTGRES_USER: cloudbp
      POSTGRES_PASSWORD: cloudbp123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cloudbp-network

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: cloudbp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cloudbp-network

  # RabbitMQ 消息队列
  rabbitmq:
    image: rabbitmq:3-management
    container_name: cloudbp-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: cloudbp
      RABBITMQ_DEFAULT_PASS: cloudbp123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - cloudbp-network

  # 后端API服务
  backend:
    build: ./backend
    container_name: cloudbp-backend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=cloudbp
      - DB_PASSWORD=cloudbp123
      - DB_NAME=cloudbp
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=cloudbp
      - RABBITMQ_PASS=cloudbp123
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - cloudbp-network
    volumes:
      - ./backend/logs:/app/logs

  # 前端应用
  frontend:
    build: ./frontend
    container_name: cloudbp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cloudbp-network

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: cloudbp-nginx
    ports:
      - "443:443"
      - "8443:8443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - cloudbp-network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  cloudbp-network:
    driver: bridge