server:
  port: "8081"
  mode: "debug"

database:
  host: "localhost"
  port: "5434"
  user: "cloudbp"
  password: "cloudbp123"
  dbname: "cloudbp"
  sslmode: "disable"

redis:
  host: "localhost"
  port: "6381"
  password: ""
  db: 0

jwt:
  secret: "your-secret-key-change-in-production"
  expire_time: 86400

log:
  level: "info"