server:
  port: "8080"
  mode: "debug"

database:
  host: "localhost"
  port: "5432"
  user: "cloudbp"
  password: "cloudbp123"
  dbname: "cloudbp"
  sslmode: "disable"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

jwt:
  secret: "your-secret-key-change-in-production"
  expire_time: 86400

log:
  level: "info"